package com.yieldbrowser.app;

/** Pure JavaScript builders extracted verbatim from MainActivity. */
final class BrowserPageScripts {
    private BrowserPageScripts() {
    }

    static String premiumAdBlock(String popupEnabled, String clickEnabled, String scriptEnabled) {
        return "javascript:(function(){"
                + "if(window.__yieldAdBlockPremiumV2){try{if(window.__yieldABRun)window.__yieldABRun();}catch(e){}return;}"
                + "window.__yieldAdBlockPremiumV2=true;window.__yieldAdBlockPremium=true;"
                + "var Y_POPUP=" + popupEnabled + ",Y_CLICK=" + clickEnabled + ",Y_SCRIPT=" + scriptEnabled + ";"
                + "function hostOf(u){try{var a=document.createElement('a');a.href=u;return (a.hostname||'').replace(/^www\\./,'').toLowerCase();}catch(e){return '';}}"
                + "function media(u){try{var s=(u||'').toLowerCase();return s.indexOf('googlevideo.com/videoplayback')>-1||s.indexOf('/videoplayback')>-1||s.indexOf('.mp4')>-1||s.indexOf('.m3u8')>-1||s.indexOf('.mpd')>-1||s.indexOf('.webm')>-1||s.indexOf('.m4s')>-1||s.indexOf('.ts')>-1||s.indexOf('mime=video')>-1||s.indexOf('mime%3dvideo')>-1;}catch(e){return false;}}"
                + "function safeVideoHost(h){return h.indexOf('youtube.com')>-1||h.indexOf('youtu.be')>-1||h.indexOf('googlevideo.com')>-1||h.indexOf('ytimg.com')>-1||h.indexOf('ggpht.com')>-1;}"
                + "function dlintent(u){try{var s=(u||'').toLowerCase();var h=hostOf(u);var trusted=h==='drive.usercontent.google.com'||h==='drive.google.com'||h==='docs.google.com'||h.endsWith('.googleusercontent.com')||h==='github.com'||h.endsWith('.githubusercontent.com')||h.endsWith('.sourceforge.net')||h.endsWith('.mediafire.com')||h.endsWith('.dropbox.com')||h.endsWith('.dropboxusercontent.com')||h==='onedrive.live.com'||h==='1drv.ms'||h==='mega.nz'||h.endsWith('.mega.nz')||h==='pixeldrain.com'||h==='gofile.io'||h==='archive.org';var marker=s.indexOf('/download')>-1||s.indexOf('download=')>-1||s.indexOf('export=download')>-1||s.indexOf('dl=1')>-1||s.indexOf('response-content-disposition=attachment')>-1||s.indexOf('content-disposition=attachment')>-1||s.indexOf('filename=')>-1||s.indexOf('confirm=')>-1||s.indexOf('uuid=')>-1||s.indexOf('/releases/download/')>-1;var file=false;var ex=['.zip','.rar','.7z','.apk','.apks','.xapk','.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.csv','.txt','.epub','.mp3','.m4a','.wav','.ogg','.mp4','.mkv','.webm','.avi','.mov','.ts','.m3u8','.iso','.img','.bin','.exe','.msi'];for(var i=0;i<ex.length;i++){if(s.indexOf(ex[i])>-1){file=true;break;}}var hard=s.indexOf('adclick')>-1||s.indexOf('ad_click')>-1||s.indexOf('adurl=')>-1||s.indexOf('click_id')>-1||s.indexOf('af_click')>-1||s.indexOf('clickunder')>-1||s.indexOf('popunder')>-1||s.indexOf('popupads')>-1||s.indexOf('onclickads')>-1||s.indexOf('interstitial')>-1||s.indexOf('utm_medium=affiliates')>-1||s.indexOf('deep_and_deferred')>-1||s.indexOf('navigate_url=')>-1||s.indexOf('reactpath')>-1;var badhost=h.endsWith('.cfd')||h.endsWith('.click')||h.endsWith('.cam')||h.endsWith('.monster')||h.endsWith('.quest')||h.endsWith('.buzz')||h.endsWith('.icu')||h.endsWith('.cyou')||h.indexOf('onclickads')>-1||h.indexOf('clickadu')>-1||h.indexOf('popads')>-1||h.indexOf('popcash')>-1||h.indexOf('propellerads')>-1||h.indexOf('adsterra')>-1||h.indexOf('hilltopads')>-1||h.indexOf('exoclick')>-1||h.indexOf('doubleclick')>-1||h.indexOf('googlesyndication')>-1||h.indexOf('googleadservices')>-1;return (trusted&&(marker||file))||((marker||file)&&!hard&&!badhost);}catch(e){return false;}}"
                + "function bad(u){try{if(!u||media(u)||dlintent(u))return false;var s=(u||'').toLowerCase();if(/^[a-z][a-z0-9+.-]*:/.test(s)&&s.indexOf('http://')!==0&&s.indexOf('https://')!==0&&s.indexOf('javascript:')!==0&&s.indexOf('data:')!==0&&s.indexOf('blob:')!==0)return true;if(/(utm_medium=affiliates|deep_and_deferred|navigate_url=|reactpath|click_id|adclick|ad_click|adurl=|af_click|tracking_id|campaign_id)/.test(s))return true;var h=hostOf(u);var cur=(location.hostname||'').replace(/^www\\./,'').toLowerCase();if(!h||h===cur||h.endsWith('.'+cur))return false;if(safeVideoHost(h))return false;if(/(hotterydiseur|sewarsremeets|onclickads|clickadu|popads|popcash|propellerads|adsterra|hilltopads|exoclick|realsrv|invest-tracing|doubleclick|googlesyndication|googleadservices)/.test(h))return true;if(/\\.(cfd|click|cam|monster|quest|buzz|icu|cyou)$/.test(h))return true;if(/\\.(shop|xyz|top|site|space|online|live|fun|lol)$/.test(h)&&/[\\/][a-z0-9_-]{8,}/.test(s))return true;if(/(popunder|popup|redirect|adclick|clickunder|interstitial|push)/.test(s))return true;return false;}catch(e){return false;}}"
                + "function visibleAnchor(a){try{if(!a||!a.getBoundingClientRect)return false;var r=a.getBoundingClientRect();var t=((a.innerText||a.textContent||a.getAttribute('aria-label')||a.title||'')+'').trim();var hasMedia=!!a.querySelector('img,svg,picture,button');return r.width>12&&r.height>8&&(t.length>0||hasMedia);}catch(e){return false;}}"
                + "function allowClickedAnchor(a,u){try{if(!a||!u)return false;var s=(u||'').toLowerCase();if(media(s)||dlintent(s))return true;var h=hostOf(u);var cur=(location.hostname||'').replace(/^www\\./,'').toLowerCase();if(!h)return false;if(h===cur||h.endsWith('.'+cur))return true;if(!visibleAnchor(a))return false;if(/(intent:|market:|shopeeid:|lazada:|tokopedia:|adclick|ad_click|adurl=|clickunder|popunder|popup|interstitial|push)/.test(s))return false;return true;}catch(e){return false;}}"
                + "if(Y_POPUP&&!window.__yieldOpenPatched){window.__yieldOpenPatched=true;var oldOpen=window.open;window.open=function(u,n,f){if(bad(u)){try{if(window.YieldAdBlockBridge)YieldAdBlockBridge.onAdRedirect(String(u));}catch(e){}return {closed:true,focus:function(){},close:function(){}};}try{return oldOpen.call(window,u,n,f);}catch(e){return {closed:true,focus:function(){},close:function(){}};}};}"
                + "if(Y_CLICK&&!window.__yieldClickPatched){window.__yieldClickPatched=true;document.addEventListener('click',function(e){try{var a=e.target&&e.target.closest?e.target.closest('a[href]'):null;if(a&&bad(a.href)&&!allowClickedAnchor(a,a.href)){try{if(window.YieldAdBlockBridge)YieldAdBlockBridge.onAdRedirect(String(a.href));}catch(ee){}e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return false;}}catch(x){}},true);document.addEventListener('auxclick',function(e){try{var a=e.target&&e.target.closest?e.target.closest('a[href]'):null;if(a&&bad(a.href)&&!allowClickedAnchor(a,a.href)){try{if(window.YieldAdBlockBridge)YieldAdBlockBridge.onAdRedirect(String(a.href));}catch(ee){}e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();return false;}}catch(x){}},true);}"
                + "function softHide(s){try{document.querySelectorAll(s).forEach(function(e){if(!e||e.tagName==='VIDEO')return;e.style.setProperty('display','none','important');e.style.setProperty('visibility','hidden','important');e.style.setProperty('height','0px','important');e.style.setProperty('min-height','0px','important');e.style.setProperty('overflow','hidden','important');});}catch(x){}}"
                + "function hardHide(s){try{document.querySelectorAll(s).forEach(function(e){if(!e||e.tagName==='VIDEO')return;e.style.setProperty('display','none','important');e.remove&&e.remove();});}catch(x){}}"
                + "function clickSkip(){try{document.querySelectorAll('.ytp-ad-skip-button,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,.ytp-skip-ad-button__button,button[class*=skip],button[id*=skip],.skip,.skip-ad,.skip-button,.vjs-skip-button,.jw-skip,.jw-skiptext,.jw-skip-icon').forEach(function(b){try{var t=(b.innerText||b.textContent||'').toLowerCase();if(t.indexOf('skip')>-1||t.indexOf('lewati')>-1||t.length<25||String(b.className).toLowerCase().indexOf('skip')>-1)b.click();}catch(e){}});}catch(e){}}"
                + "function isYT(){var h=(location.hostname||'').toLowerCase();return h.indexOf('youtube.com')>-1||h.indexOf('youtu.be')>-1;}"
                + "function isYouTubeAd(){try{var p=document.querySelector('.html5-video-player');var cls=p?String(p.className):'';return cls.indexOf('ad-showing')>-1||cls.indexOf('ad-interrupting')>-1||!!document.querySelector('.ytp-ad-skip-button,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,.ytp-ad-text,.ytp-ad-image-overlay,.ytp-ad-player-overlay');}catch(e){return false;}}"
                + "function isGenericVideoAd(){try{var s=(document.body&&document.body.innerText||'').toLowerCase();var text=/(advertisement|sponsored|iklan|ads? will end|ad will end|skip ad|lewati iklan|continue to video)/.test(s);var el=!!document.querySelector('.vast,.vpaid,.ima-ad-container,.ima-ad,.googleima,.ad-container,.ad-overlay,.video-ads,.preroll,.pre-roll,.midroll,.mid-roll,.jw-ad,.jw-flag-ads,.jw-ad-visible,.vjs-ad-playing,.vjs-ima3-ad-container,.vjs-ad-container,.plyr__ads,.ad-player,.ad-wrapper,[class*=vast],[class*=vpaid],[class*=preroll],[class*=midroll],[id*=preroll],[id*=midroll]');return text||el;}catch(e){return false;}}"
                + "function safeSpeedAd(v,fast){try{if(!v)return;if(!v.__yieldAdSaved){v.__yieldWasMuted=v.muted;v.__yieldWasRate=v.playbackRate||1;v.__yieldAdSaved=true;v.__yieldAdTicks=0;}v.__yieldAdTicks=(v.__yieldAdTicks||0)+1;v.muted=true;try{v.defaultMuted=true;}catch(e){}try{v.playbackRate=Math.max(fast,16);}catch(e){}try{v.defaultPlaybackRate=Math.max(fast,16);}catch(e){}v.play&&v.play().catch(function(){});if(isFinite(v.duration)&&v.duration>1&&v.duration<240){var cur=isFinite(v.currentTime)?v.currentTime:0;var step=v.__yieldAdTicks>3?20:12;var target=cur+step;if(v.__yieldAdTicks>7&&v.duration<90)target=v.duration-0.18;var next=Math.min(v.duration-0.12,target);if(next>cur){v.currentTime=next;try{v.dispatchEvent(new Event('seeking'));v.dispatchEvent(new Event('timeupdate'));}catch(e){}}}}catch(e){}}"
                + "function restoreVideo(v){try{if(v&&v.__yieldAdSaved){v.muted=!!v.__yieldWasMuted;try{v.defaultMuted=!!v.__yieldWasMuted;}catch(e){}v.playbackRate=v.__yieldWasRate||1;try{v.defaultPlaybackRate=v.__yieldWasRate||1;}catch(e){}v.__yieldAdSaved=false;v.__yieldAdTicks=0;}}catch(e){}}"
                + "function hideYouTubeSponsorBlocks(){try{var sels=['ytm-promoted-video-renderer','ytm-promoted-sparkles-web-renderer','ytm-ad-slot-renderer','ytm-companion-slot-renderer','ytd-promoted-video-renderer','ytd-display-ad-renderer','ytd-ad-slot-renderer','ytd-companion-slot-renderer','#player-ads'];sels.forEach(function(s){try{document.querySelectorAll(s).forEach(function(e){if(!e||e.querySelector('video'))return;e.style.setProperty('display','none','important');e.style.setProperty('height','0px','important');e.style.setProperty('overflow','hidden','important');});}catch(x){}});}catch(e){}}"
                + "function bypassVideoAds(){try{clickSkip();var yt=isYT()&&isYouTubeAd();var gen=!yt&&isGenericVideoAd();var v=document.querySelector('video');if(yt){safeSpeedAd(v,16);softHide('.ytp-ad-overlay-container,.ytp-ad-text,.ytp-ad-image-overlay');return;}if(gen){safeSpeedAd(v,8);hardHide('.ima-ad-container,.ima-ad,.googleima,.ad-overlay,.video-ads,.preroll,.pre-roll,.midroll,.mid-roll,.jw-ad,.jw-ad-visible,.vjs-ima3-ad-container,.vjs-ad-container,.plyr__ads,.ad-player,.ad-wrapper,[class*=vast],[class*=vpaid]');return;}restoreVideo(v);}catch(e){}}"
                + "function ytState(){try{window.__yieldYTAdV2=window.__yieldYTAdV2||{active:false,lastAd:0,ticks:0,skipClicks:0};return window.__yieldYTAdV2;}catch(e){return {active:false,lastAd:0,ticks:0};}}"
                + "function repairYouTubeVisibility(){try{['html','body','#player','#movie_player','.html5-video-player','video','ytm-app','ytd-app','#app','#content','#contents'].forEach(function(s){document.querySelectorAll(s).forEach(function(e){try{e.style.removeProperty('display');e.style.removeProperty('visibility');e.style.removeProperty('height');e.style.removeProperty('min-height');e.style.removeProperty('opacity');}catch(x){}});});}catch(e){}}"
                + "function installYouTubeSafeStyle(){try{if(document.getElementById('yield-yt-safe-ad-style'))return;var st=document.createElement('style');st.id='yield-yt-safe-ad-style';st.textContent='.ytp-ad-overlay-container,.ytp-ad-text,.ytp-ad-image-overlay,.ytp-ad-player-overlay,.ytp-ad-player-overlay-instream-info,.ytp-ad-preview-container,.ytp-ad-action-interstitial,.ytp-ad-survey,.ytp-ad-progress-list,.ytp-ad-button,.ytp-ad-badge,.ytp-paid-content-overlay,ytd-player-legacy-desktop-watch-ads-renderer,ytd-action-companion-ad-renderer,ytd-display-ad-renderer,ytd-promoted-video-renderer,ytd-ad-slot-renderer,ytd-companion-slot-renderer,ytm-promoted-video-renderer,ytm-promoted-sparkles-web-renderer,ytm-ad-slot-renderer,ytm-companion-slot-renderer,#player-ads{display:none!important;visibility:hidden!important;opacity:0!important;pointer-events:none!important;max-height:0!important;overflow:hidden!important;}';(document.head||document.documentElement).appendChild(st);}catch(e){}}"
                + "function ytAdVideo(){try{return document.querySelector('.html5-video-player.ad-showing video,.html5-video-player.ad-interrupting video,#movie_player.ad-showing video,#movie_player.ad-interrupting video')||document.querySelector('#movie_player video')||document.querySelector('video');}catch(e){return null;}}"
                + "function youtubeAdSignalV2(){try{var p=document.querySelector('.html5-video-player,#movie_player');var cls=p?String(p.className||''):'';if(/ad-showing|ad-interrupting|ad-created|ad-playing/.test(cls))return true;var q='.ytp-ad-skip-button,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,.ytp-skip-ad-button__button,.ytp-ad-preview-container,.ytp-ad-player-overlay,.ytp-ad-player-overlay-instream-info,.ytp-ad-text,.ytp-ad-image-overlay,.ytp-ad-simple-ad-badge,.ytp-ad-badge,.ytp-ad-action-interstitial,.ytp-ad-survey,.video-ads.ytp-ad-module';if(document.querySelector(q))return true;var t=((document.querySelector('.ytp-ad-text,.ytp-ad-preview-text,.ytp-ad-simple-ad-badge,.ytp-ad-badge')||{}).textContent||'').toLowerCase();return /(ad|ads|iklan|sponsored|skip|lewati)/.test(t);}catch(e){return false;}}"
                + "function clickYouTubeSkipV2(){try{var sels=['.ytp-ad-skip-button','.ytp-ad-skip-button-modern','.ytp-skip-ad-button','.ytp-skip-ad-button__button','.ytm-ad-skip-button','button[aria-label*=\"Skip\"]','button[aria-label*=\"skip\"]','button[aria-label*=\"Lewati\"]','button[aria-label*=\"lewati\"]','button[class*=skip]'];sels.forEach(function(s){document.querySelectorAll(s).forEach(function(b){try{if(!b||b.disabled)return;var r=b.getBoundingClientRect?b.getBoundingClientRect():{width:1,height:1};var txt=((b.innerText||b.textContent||b.getAttribute('aria-label')||b.title||'')+'').toLowerCase();if(r.width>=0&&r.height>=0&&(txt.indexOf('skip')>-1||txt.indexOf('lewati')>-1||String(b.className).toLowerCase().indexOf('skip')>-1)){b.click();ytState().skipClicks++;}}catch(x){}});});}catch(e){}}"
                + "function fastForwardYouTubeAdV2(v){try{var st=ytState();if(!v)return;var now=Date.now();st.lastAd=now;st.ticks=(st.ticks||0)+1;if(!st.active){st.active=true;st.savedMuted=v.muted;st.savedRate=v.playbackRate||1;st.savedDefaultRate=v.defaultPlaybackRate||1;st.savedVolume=v.volume;}try{v.muted=true;v.defaultMuted=true;if(v.volume>0.01)v.volume=0;}catch(e){}try{v.playbackRate=16;v.defaultPlaybackRate=16;}catch(e){}try{if(v.paused&&v.play)v.play().catch(function(){});}catch(e){}try{if(isFinite(v.duration)&&v.duration>1&&v.duration<240){var cur=isFinite(v.currentTime)?v.currentTime:0;var jump=st.ticks>2?18:8;var target=cur+jump;if(st.ticks>5||st.skipClicks>0)target=v.duration-0.16;var next=Math.min(v.duration-0.12,target);if(next>cur){v.currentTime=next;v.dispatchEvent(new Event('timeupdate'));}}}catch(e){}}catch(e){}}"
                + "function restoreYouTubeVideoV2(v){try{var st=ytState();if(!st.active)return;if(Date.now()-(st.lastAd||0)<1700)return;if(v){try{v.muted=!!st.savedMuted;v.defaultMuted=!!st.savedMuted;}catch(e){}try{if(isFinite(st.savedVolume))v.volume=st.savedVolume;}catch(e){}try{v.playbackRate=st.savedRate||1;v.defaultPlaybackRate=st.savedDefaultRate||st.savedRate||1;}catch(e){}}st.active=false;st.ticks=0;st.skipClicks=0;}catch(e){}}"
                + "function bypassYouTubeAdsV2(){try{if(!isYT())return false;repairYouTubeVisibility();installYouTubeSafeStyle();clickYouTubeSkipV2();clickSkip();var v=ytAdVideo();var ad=youtubeAdSignalV2();if(ad){softHide('.ytp-ad-overlay-container,.ytp-ad-text,.ytp-ad-image-overlay,.ytp-ad-player-overlay,.ytp-ad-player-overlay-instream-info,.ytp-ad-preview-container,.ytp-ad-action-interstitial,.ytp-ad-survey');fastForwardYouTubeAdV2(v);return true;}restoreYouTubeVideoV2(v);return false;}catch(e){return false;}}"
                + "function bypassVideoAdsV2(){try{if(bypassYouTubeAdsV2())return;var gen=isGenericVideoAd();var v=document.querySelector('video');if(gen){safeSpeedAd(v,8);hardHide('.ima-ad-container,.ima-ad,.googleima,.ad-overlay,.video-ads,.preroll,.pre-roll,.midroll,.mid-roll,.jw-ad,.jw-ad-visible,.vjs-ima3-ad-container,.vjs-ad-container,.plyr__ads,.ad-player,.ad-wrapper,[class*=vast],[class*=vpaid]');return;}restoreVideo(v);}catch(e){}}"
                + "function setupYouTubeAdObserver(){try{if(window.__yieldYTAdObserverInstalled)return;window.__yieldYTAdObserverInstalled=true;var run=function(){try{bypassYouTubeAdsV2();}catch(e){}};var mo=new MutationObserver(function(){run();});mo.observe(document.documentElement||document,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','aria-label']});document.addEventListener('yt-navigate-finish',function(){setTimeout(run,80);setTimeout(run,500);},true);document.addEventListener('visibilitychange',run,true);setInterval(run,180);}catch(e){}}"
                + "function clean(){"
                + "var yt=isYT();try{if(yt){['html','body','ytm-app','ytd-app','#app','#content','#contents','ytm-browse','ytm-watch','ytm-single-column-watch-next-results-renderer','ytm-item-section-renderer','ytm-rich-grid-renderer','ytm-video-with-context-renderer','ytm-playlist-video-renderer','ytm-slim-video-metadata-renderer','ytm-watch-metadata','ytd-page-manager','ytd-watch-flexy','ytd-rich-grid-renderer'].forEach(function(s){document.querySelectorAll(s).forEach(function(e){e.style.removeProperty('display');e.style.removeProperty('visibility');e.style.removeProperty('height');e.style.removeProperty('min-height');e.style.removeProperty('overflow');e.style.removeProperty('opacity');});});}}catch(e){}try{if(yt&&document.body&&document.body.innerText.trim().length<20&&document.querySelector('ytm-app')){['html','body','ytm-app','#app','#content','#contents'].forEach(function(s){document.querySelectorAll(s).forEach(function(e){e.style.cssText=e.style.cssText.replace(/display\\s*:\\s*none\\s*!important;?/gi,'').replace(/height\\s*:\\s*0px\\s*!important;?/gi,'').replace(/visibility\\s*:\\s*hidden\\s*!important;?/gi,'');});});}}catch(e){}bypassVideoAdsV2();if(yt){hideYouTubeSponsorBlocks();setupYouTubeAdObserver();}"
                + "try{if(Y_CLICK)document.querySelectorAll('a[target=_blank],a[target=\\\"_blank\\\"]').forEach(function(a){if(bad(a.href)){a.removeAttribute('target');a.setAttribute('rel','noopener noreferrer');}});}catch(e){}"
                + "var selectors=yt?["
                + "'ytd-display-ad-renderer','ytd-promoted-video-renderer','ytd-ad-slot-renderer','ytd-companion-slot-renderer','ytd-banner-promo-renderer','ytd-in-feed-ad-layout-renderer','ytd-promoted-sparkles-web-renderer','ytm-promoted-sparkles-web-renderer','ytm-promoted-video-renderer','ytm-ad-slot-renderer','ytm-companion-slot-renderer','ytm-in-feed-ad-layout-renderer','ytm-display-ad-renderer','#player-ads','.ytp-ad-overlay-container','.ytp-ad-text','.ytp-ad-image-overlay','.ytp-ad-progress-list','.GoogleActiveViewElement'"
                + "]:["
                + "'.adsbygoogle','iframe[id*=ad]','iframe[src*=ads]','iframe[src*=doubleclick]','iframe[src*=onclickads]','iframe[src*=clickadu]','iframe[src*=popads]','iframe[src*=propellerads]','[id*=ad-]','[id^=ad_]','[class*=ad-]','[class*=ads-]','[class*=advert]','.GoogleActiveViewElement','.ad-banner','.ad-container','.advertisement','.sponsored','.ima-ad-container','.ima-ad','.googleima','.ad-overlay','.video-ads','.preroll','.pre-roll','.midroll','.mid-roll','.vjs-ima3-ad-container','.vjs-ad-container','.plyr__ads'"
                + "];"
                + "if(Y_SCRIPT&&yt){selectors.forEach(hardHide);}"
                + "try{if(Y_SCRIPT)document.querySelectorAll('iframe[src],script[src]').forEach(function(el){var u=el.src||'';if(bad(u)){el.remove();}});}catch(e){}"
                + "try{document.body.style.setProperty('overflow','auto','important');}catch(e){}"
                + "}"
                + "window.__yieldABRun=clean;"
                + "var __abP=false;function __abS(){if(__abP)return;__abP=true;(window.requestAnimationFrame||function(f){setTimeout(f,16);})(function(){__abP=false;try{clean();}catch(e){}});}"
                + "try{if(window.__yieldABObs&&window.__yieldABObs.disconnect)window.__yieldABObs.disconnect();}catch(e){}"
                + "try{window.__yieldABObs=new MutationObserver(function(){__abS();});window.__yieldABObs.observe(document.documentElement||document.body||document,{childList:true,subtree:true});}catch(e){}"
                + "try{if(window.__yieldABInt)clearInterval(window.__yieldABInt);}catch(e){}"
                + "window.__yieldABInt=setInterval(function(){try{if(document.querySelector('video'))clean();}catch(e){}},700);"
                + "clean();setTimeout(clean,120);setTimeout(clean,500);setTimeout(clean,1500);setTimeout(clean,3500);"
                + "})();";
    }

    static String youtubeSafeAdBlock() {
        return "javascript:"
                + "(function(){\n"
                + "try{\n"
                + "  var h=(location.hostname||'').toLowerCase();\n"
                + "  if(h.indexOf('youtube.com')<0 && h.indexOf('youtu.be')<0) return;\n"
                + "  var W=window;\n"
                + "  W.__yieldYTAssistantDisabled=false;\n"
                + "  W.__yieldYTNoForcePlay=true;\n"
                + "  if(W.__yieldYTAutoCycleV70){try{W.__yieldYTAutoCycleV70.phase='monitor';W.__yieldYTAutoCycleV70.lastAdSeen=0;W.__yieldYTAutoCycleV70.coolStart=0;W.__yieldYTAutoCycleV70.hadAd=false;}catch(e){}}\n"
                + "  W.__yieldYTPassiveResume=W.__yieldYTPassiveResume||{installed:false,lastUrl:'',lastSkipAt:0,resumeUntil:0,lastUserInputAt:0,lastResumeAt:0,lastAdSeekAt:0,lastAdPlayAt:0,lastAdSeenAt:0,hadAd:false};\n"
                + "  var S=W.__yieldYTPassiveResume;\n"
                + "  if(S.lastUrl!==location.href){S.lastUrl=location.href;S.lastSkipAt=0;S.resumeUntil=0;S.lastUserInputAt=0;S.lastResumeAt=0;S.lastAdSeekAt=0;S.lastAdPlayAt=0;S.lastAdSeenAt=0;S.hadAd=false;}\n"
                + "  function now(){return Date.now?Date.now():(new Date()).getTime();}\n"
                + "  function qsa(s,r){try{return Array.prototype.slice.call((r||document).querySelectorAll(s));}catch(e){return [];} }\n"
                + "  function visible(el){try{if(!el)return false;var r=el.getBoundingClientRect();var cs=getComputedStyle(el);return r.width>1&&r.height>1&&cs.display!=='none'&&cs.visibility!=='hidden'&&parseFloat(cs.opacity||'1')>0.01;}catch(e){return !!el;} }\n"
                + "  function txt(el){try{return ((el.innerText||el.textContent||el.getAttribute('aria-label')||el.getAttribute('title')||'')+'').replace(/\\s+/g,' ').trim().toLowerCase();}catch(e){return '';} }\n"
                + "  function player(){try{return document.querySelector('#movie_player,.html5-video-player,ytd-player,ytm-player,#player-container-id,#player-container,#player');}catch(e){return null;}}\n"
                + "  function video(){try{return document.querySelector('#movie_player video,.html5-video-player video,ytd-player video,ytm-player video,#player video,video');}catch(e){return null;}}\n"
                + "  function adShowing(){try{var p=player();var cls=p?String(p.className||''):'';var root=p||document;var skip=qsa('.ytp-ad-skip-button,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,.ytp-skip-ad-button__button,.ytm-ad-skip-button',root).some(visible);var ui=qsa('.ytp-ad-player-overlay,.ytp-ad-player-overlay-instream-info,.ytp-ad-preview-container,.ytp-ad-text,.ytp-ad-simple-ad-badge,.ytp-ad-badge,.video-ads.ytp-ad-module,.ytp-ad-action-interstitial',root).some(visible);var pt=txt(root);var word=/(bersponsor|sponsored|kunjungi pengiklan|visit advertiser|lewati iklan|skip ad|iklan\\s*\\u2022|ad\\s*1\\s*of|ad\\s*2\\s*of|1\\s*dari\\s*2|2\\s*dari\\s*2)/i.test(pt);return cls.indexOf('ad-showing')>-1||cls.indexOf('ad-interrupting')>-1||skip||ui||word;}catch(e){return false;}}\n"
                + "  function installStyle(){try{if(document.getElementById('yield-yt-passive-style'))return;var st=document.createElement('style');st.id='yield-yt-passive-style';st.textContent='ytd-display-ad-renderer,ytd-promoted-video-renderer,ytd-ad-slot-renderer,ytd-companion-slot-renderer,ytd-banner-promo-renderer,ytd-in-feed-ad-layout-renderer,ytd-promoted-sparkles-web-renderer,ytm-promoted-sparkles-web-renderer,ytm-promoted-video-renderer,ytm-ad-slot-renderer,ytm-companion-slot-renderer,ytm-in-feed-ad-layout-renderer,ytm-display-ad-renderer,#player-ads,.ytp-ad-overlay-container,.ytp-ad-text,.ytp-ad-image-overlay,.ytp-ad-progress-list{display:none!important;visibility:hidden!important;opacity:0!important;max-height:0!important;overflow:hidden!important;}';(document.head||document.documentElement).appendChild(st);}catch(e){}}\n"
                + "  function cleanCards(){try{installStyle();qsa('ytd-display-ad-renderer,ytd-promoted-video-renderer,ytd-ad-slot-renderer,ytd-companion-slot-renderer,ytd-banner-promo-renderer,ytd-in-feed-ad-layout-renderer,ytd-promoted-sparkles-web-renderer,ytm-promoted-sparkles-web-renderer,ytm-promoted-video-renderer,ytm-ad-slot-renderer,ytm-companion-slot-renderer,ytm-in-feed-ad-layout-renderer,ytm-display-ad-renderer,#player-ads').forEach(function(e){try{if(e.querySelector&&e.querySelector('video'))return;e.style.setProperty('display','none','important');e.style.setProperty('visibility','hidden','important');e.style.setProperty('height','0px','important');e.style.setProperty('max-height','0px','important');e.style.setProperty('overflow','hidden','important');}catch(x){}});}catch(e){}}\n"
                + "  function resumeAfterSkipOnce(){try{if(W.__yieldYTAssistantDisabled)return false;var t=now();if(!S.resumeUntil||t>S.resumeUntil)return false;if((S.lastResumeAt||0)>(S.lastSkipAt||0))return false;if((S.lastUserInputAt||0)>(S.lastSkipAt||0)+80)return false;if(adShowing())return false;var v=video();if(!v||v.ended||!v.paused)return false;S.lastResumeAt=t;var p=v.play&&v.play();if(p&&p.catch)p.catch(function(){});return true;}catch(e){return false;}}\n"
                + "  function scheduleResumeAfterSkip(){try{if(W.__yieldYTAssistantDisabled)return;S.lastSkipAt=now();S.resumeUntil=S.lastSkipAt+4500;S.lastResumeAt=0;[550,1200,2200,3400].forEach(function(d){setTimeout(resumeAfterSkipOnce,d);});}catch(e){}}\n"
                + "  function nodeInfo(el){try{var out='';var n=el;var p=player();for(var i=0;n&&i<5;i++,n=n.parentElement){if(p&&n===p&&n!==el)break;out+=' '+txt(n)+' '+String(n.className||'')+' '+String(n.id||'')+' '+String(n.getAttribute&&n.getAttribute('aria-label')||'')+' '+String(n.getAttribute&&n.getAttribute('title')||'')+' '+String(n.getAttribute&&n.getAttribute('data-title-no-tooltip')||'');}return out.toLowerCase();}catch(e){return '';}}\n"
                + "  function badSkipTarget(el){try{var s=nodeInfo(el);return /(kunjungi|visit|situs|site|advertiser|pengiklan|sponsor|bersponsor|cta|call-to-action|menu|more|overflow|setting|quality|caption|subtitle|mute|volume|fullscreen|share|like|subscribe|search|account|buka apl|open app)/i.test(s)&&!/(skip|lewati|ad-skip|skip-ad|ytp-ad-skip)/i.test(s);}catch(e){return true;}}\n"
                + "  function skipLike(el){try{return /(skip|lewati|ad-skip|skip-ad|ytp-ad-skip|ytp-skip-ad|ad_skip|skip_button|skipbutton)/i.test(nodeInfo(el));}catch(e){return false;}}\n"
                + "  function tapSkip(el){try{if(!el||!visible(el)||el.disabled||badSkipTarget(el))return false;try{el.scrollIntoView&&el.scrollIntoView({block:'nearest',inline:'nearest'});}catch(x){}try{['pointerdown','mousedown','mouseup','touchstart','touchend','click'].forEach(function(ev){try{el.dispatchEvent(new Event(ev,{bubbles:true,cancelable:true}));}catch(e){}});}catch(x){}try{el.click&&el.click();}catch(x){}scheduleResumeAfterSkip();return true;}catch(e){return false;}}\n"
                + "  function iconSkipFallback(root){try{if(!adShowing())return false;var p=player();if(!p)return false;var pr=p.getBoundingClientRect();var list=qsa('button,[role=button],.ytp-button,.ytp-ad-button-icon,.ytp-ad-skip-button-icon,.ytp-ad-skip-button-modern,.ytp-skip-ad-button,.ytp-skip-ad-button__button',root||p);for(var i=0;i<list.length;i++){var b=list[i];try{if(!visible(b)||b.disabled||badSkipTarget(b))continue;var info=nodeInfo(b);if(/(skip|lewati|ad-skip|skip-ad|ytp-ad-skip|ytp-skip-ad|ad_skip)/i.test(info))return tapSkip(b);var r=b.getBoundingClientRect();var right=r.left>pr.left+pr.width*0.54&&r.right<=pr.right+8;var mid=r.top>pr.top+pr.height*0.18&&r.bottom<pr.bottom-pr.height*0.08;var size=r.width>=22&&r.height>=22&&r.width<=150&&r.height<=100;var icon=!!(b.querySelector&&b.querySelector('svg,path,use,yt-icon'))||/(icon|button|ytp)/i.test(String(b.className||''));if(right&&mid&&size&&icon)return tapSkip(b);}catch(x){}}return false;}catch(e){return false;}}\n"
                + "  function clickSkipOnly(){try{if(W.__yieldYTAssistantDisabled)return false;var root=player()||document;var sels=['.ytp-ad-skip-button','.ytp-ad-skip-button-modern','.ytp-ad-skip-button-container','.ytp-ad-skip-button-slot','.ytp-skip-ad-button','.ytp-skip-ad-button__button','.ytm-ad-skip-button','.ytp-ad-skip-button-icon','.ytp-ad-button-icon','button[aria-label*=\"Skip\"]','button[aria-label*=\"skip\"]','button[aria-label*=\"Lewati\"]','button[aria-label*=\"lewati\"]','[class*=\"ad-skip\"]','[class*=\"skip-ad\"]','[id*=\"ad-skip\"]','[id*=\"skip-ad\"]'];var clicked=false;sels.forEach(function(sel){qsa(sel,root).forEach(function(b){try{if(clicked||!visible(b)||b.disabled)return;if(skipLike(b)||/skip|lewati/i.test(txt(b))){clicked=tapSkip(b);}}catch(x){}});});if(!clicked)clicked=iconSkipFallback(root);return clicked;}catch(e){return false;}}\n"
                + "  function forwardAd10sSafe(){try{if(W.__yieldYTAssistantDisabled)return false;if(!adShowing())return false;var v=video();if(!v||v.ended)return false;var t=now();S.lastAdSeenAt=t;S.hadAd=true;if(v.paused&&t-(S.lastAdPlayAt||0)>1200){S.lastAdPlayAt=t;try{var p0=v.play&&v.play();if(p0&&p0.catch)p0.catch(function(){});}catch(x){}}if(t-(S.lastAdSeekAt||0)<850)return false;var cur=Number(v.currentTime||0);var dur=Number(v.duration||0);if(!isFinite(cur))return false;S.lastAdSeekAt=t;try{var pl=player();if(pl&&pl.focus)pl.focus();var ev=new KeyboardEvent('keydown',{key:'l',code:'KeyL',keyCode:76,which:76,bubbles:true,cancelable:true});document.dispatchEvent(ev);}catch(x){}try{if(isFinite(dur)&&dur>0){v.currentTime=Math.min(Math.max(cur+10,cur),Math.max(0,dur-0.15));}else{v.currentTime=cur+10;}}catch(x){}return true;}catch(e){return false;}}\n"
                + "  function run(){try{if(W.__yieldYTAssistantDisabled)return;cleanCards();var clicked=clickSkipOnly();if(!clicked)forwardAd10sSafe();resumeAfterSkipOnce();}catch(e){}}\n"
                + "  W.__yieldYTPassiveRun=run;\n"
                + "  if(!S.installed){S.installed=true;['pointerdown','touchstart','mousedown','keydown'].forEach(function(ev){try{document.addEventListener(ev,function(e){try{if(!e||e.isTrusted)S.lastUserInputAt=now();}catch(x){}},true);}catch(e){}});try{var tm=null;var mo=new MutationObserver(function(){clearTimeout(tm);tm=setTimeout(run,120);});mo.observe(document.documentElement||document,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','aria-label','title']});}catch(e){} ['yt-navigate-finish','yt-page-data-updated','spfdone'].forEach(function(ev){try{document.addEventListener(ev,function(){setTimeout(run,120);setTimeout(run,700);},true);}catch(e){}});setInterval(run,900);}\n"
                + "  setTimeout(run,80);setTimeout(run,400);setTimeout(run,1200);setTimeout(run,3000);\n"
                + "}catch(e){}\n"
                + "})();\n";
    }

    static String stopYouTubeAssistant() {
        return "javascript:"
                + "(function(){try{"
                + "window.__yieldYTAssistantDisabled=true;"
                + "window.__yieldYTNoForcePlay=true;"
                + "if(window.__yieldYTPassiveResume){"
                + "window.__yieldYTPassiveResume.lastSkipAt=0;"
                + "window.__yieldYTPassiveResume.resumeUntil=0;"
                + "window.__yieldYTPassiveResume.lastResumeAt=0;"
                + "window.__yieldYTPassiveResume.lastAdSeekAt=0;"
                + "window.__yieldYTPassiveResume.lastAdPlayAt=0;"
                + "window.__yieldYTPassiveResume.lastAdSeenAt=0;"
                + "window.__yieldYTPassiveResume.hadAd=false;"
                + "}"
                + "window.__yieldYTPassiveRun=function(){};"
                + "var st=document.getElementById('yield-yt-passive-style');"
                + "if(st&&st.parentNode)st.parentNode.removeChild(st);"
                + "}catch(e){}})();";
    }

    static String videoPlaybackWatcher(boolean youtubePage,
                                       boolean videoBufferBooster,
                                       boolean hlsSegmentPrefetch,
                                       boolean videoBackgroundPlay) {
        return "javascript:(function(){"
                + "window.__yieldVideoWatcherInstalled=true;"
                + "var Y_BUF=" + (!youtubePage && videoBufferBooster ? "true" : "false") + ",Y_HLS=" + (!youtubePage && hlsSegmentPrefetch ? "true" : "false") + ",Y_BG=" + (!youtubePage && videoBackgroundPlay ? "true" : "false") + ";"
                + "function qOf(s){s=(s||'').toLowerCase();var m=s.match(/(240|360|480|720|1080)p|height=(240|360|480|720|1080)|res=(240|360|480|720|1080)|quality=(240|360|480|720|1080)/);return m?(m[1]||m[2]||m[3]||m[4]||''):'';}"
                + "function collectQ(v){try{var out=[];var ss=v.querySelectorAll('source[src]');for(var i=0;i<ss.length;i++){var q=qOf((ss[i].src||'')+' '+(ss[i].getAttribute('label')||'')+' '+(ss[i].getAttribute('res')||''));if(q&&out.indexOf(q)<0)out.push(q);}try{if(window.jwplayer){var j=window.jwplayer();var lv=j.getQualityLevels?j.getQualityLevels():[];for(var a=0;a<lv.length;a++){var q=(lv[a].height||lv[a].label||'')+'';q=q.replace(/[^0-9]/g,'');if(q&&out.indexOf(q)<0)out.push(q);}}}catch(e){}try{if(window.videojs){var ps=window.videojs.getPlayers?window.videojs.getPlayers():{};for(var k in ps){var p=ps[k];if(p&&p.qualityLevels){var ql=p.qualityLevels();for(var b=0;b<ql.length;b++){var h=(ql[b].height||'')+'';if(h&&out.indexOf(h)<0)out.push(h);}}}}}catch(e){}if(out.length){window.__yieldVideoQualities=out.sort(function(a,b){return parseInt(a)-parseInt(b);});}}catch(e){}}"
                + "function prefetch(u){try{if(!Y_HLS||!u||window.__yieldPrefetch&&window.__yieldPrefetch[u])return;if(!window.__yieldPrefetch)window.__yieldPrefetch={};window.__yieldPrefetch[u]=true;fetch(u,{method:'GET',mode:'no-cors',cache:'force-cache'}).catch(function(){});}catch(e){}}"
                + "function hlsProbe(v){try{if(!Y_HLS)return;var u=(v.currentSrc||v.src||'');if(u&&u.indexOf('.m3u8')>-1)prefetch(u);document.querySelectorAll('source[src]').forEach(function(s){var x=s.src||'';if(x.indexOf('.m3u8')>-1)prefetch(x);});performance.getEntriesByType('resource').slice(-40).forEach(function(r){var x=r.name||'';if(x.indexOf('.m3u8')>-1||x.indexOf('.ts')>-1||x.indexOf('.m4s')>-1)prefetch(x);});}catch(e){}}"
                + "function boost(v){try{if(Y_BUF){v.preload='auto';v.setAttribute('preload','auto');try{v.load();}catch(e){}}if(Y_BG){document.addEventListener('visibilitychange',function(){try{if(document.hidden&&v&&!v.paused){setTimeout(function(){try{v.play();}catch(e){}},250);}}catch(e){}},true);}}catch(e){}}"
                + "function hook(v){"
                + " if(!v||v.__yieldHooked)return;"
                + " v.__yieldHooked=true;"
                + " boost(v);collectQ(v);hlsProbe(v);"
                + " var show=function(){try{collectQ(v);hlsProbe(v);if(window.YieldVideoBridge)YieldVideoBridge.onVideoPlaying();}catch(e){}};"
                + " var tap=function(){try{if(window.YieldVideoBridge)YieldVideoBridge.onVideoTapped();}catch(e){}};"
                + " var hide=function(){try{if(window.YieldVideoBridge)YieldVideoBridge.onVideoStopped();}catch(e){}};"
                + " v.addEventListener('play',show,true);"
                + " v.addEventListener('playing',show,true);"
                + " v.addEventListener('loadedmetadata',show,true);"
                + " v.addEventListener('loadeddata',show,true);"
                + " v.addEventListener('canplay',show,true);"
                + " v.addEventListener('click',tap,true);"
                + " v.addEventListener('touchend',tap,true);"
                + " v.addEventListener('pause',hide,true);"
                + " v.addEventListener('ended',hide,true);"
                + " if(!v.paused&&!v.ended&&v.readyState>2)show();"
                + "}"
                + "function scan(){try{var vs=document.querySelectorAll('video');for(var i=0;i<vs.length;i++){hook(vs[i]);}}catch(e){}}"
                + "scan();setInterval(scan,2500);"
                + "try{new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});}catch(e){}"
                + "})()";
    }

    static String videoQuality(String target) {
        return
                "(function(){"
                        + "try{"
                        + "var target='" + target + "';"
                        + "var video=null;"
                        + "var videos=document.querySelectorAll('video');"
                        + "for(var i=0;i<videos.length;i++){var r=videos[i].getBoundingClientRect();if(r.width>60&&r.height>40){video=videos[i];break;}}"
                        + "if(!video&&videos.length>0)video=videos[0];"
                        + "if(!video)return 'no_video';"
                        + "var current=0;try{current=video.currentTime||0;}catch(e){}"
                        + "var paused=true;try{paused=video.paused;}catch(e){}"
                        + "function hasQ(s){s=(s||'').toLowerCase();return s.indexOf(target+'p')>-1||s.indexOf(target+'_')>-1||s.indexOf(target+'-')>-1||s.indexOf(target+'.')>-1||s.indexOf('height='+target)>-1||s.indexOf('res='+target)>-1||s.indexOf('quality='+target)>-1;}"
                        + "function switchSrc(src,type){try{if(!src)return false;video.pause();video.src=src;if(type)video.type=type;video.load();video.addEventListener('loadedmetadata',function(){try{video.currentTime=current;if(!paused)video.play();}catch(e){}},{once:true});return true;}catch(e){return false;}}"
                        + "var sources=video.querySelectorAll('source[src]');"
                        + "for(var s=0;s<sources.length;s++){var src=sources[s].src||sources[s].getAttribute('src')||'';var label=(sources[s].getAttribute('label')||sources[s].getAttribute('res')||sources[s].getAttribute('data-quality')||'');if(hasQ(src)||hasQ(label)){if(switchSrc(src,sources[s].type||''))return 'changed_source';}}"
                        + "var vsrc=video.currentSrc||video.src||'';"
                        + "if(hasQ(vsrc))return 'already';"
                        + "try{if(window.jwplayer){var j=window.jwplayer();var levels=j.getQualityLevels?j.getQualityLevels():[];for(var jx=0;jx<levels.length;jx++){var q=(levels[jx].label||levels[jx].height||'')+'';if(hasQ(q)){j.setCurrentQuality(jx);return 'changed_jwplayer';}}}}catch(e){}"
                        + "try{if(window.videojs){var players=window.videojs.getPlayers?window.videojs.getPlayers():{};for(var k in players){var p=players[k];if(p&&p.qualityLevels){var ql=p.qualityLevels();for(var qi=0;qi<ql.length;qi++){var h=(ql[qi].height||'')+'';if(hasQ(h)){for(var qj=0;qj<ql.length;qj++)ql[qj].enabled=false;ql[qi].enabled=true;return 'changed_videojs';}}}}}}catch(e){}"
                        + "var clickables=document.querySelectorAll('button,[role=button],li,a,span,div');"
                        + "for(var c=0;c<clickables.length&&c<800;c++){var t=(clickables[c].innerText||clickables[c].textContent||clickables[c].getAttribute('aria-label')||'').trim();if(hasQ(t)&&t.length<40){try{clickables[c].click();return 'clicked_quality';}catch(e){}}}"
                        + "return 'not_found';"
                        + "}catch(e){return 'error';}"
                        + "})()";
    }

    static String videoControl(String action) {
        if ("play".equals(action)) {
            return "(function(){var v=document.querySelector('video');if(v){v.play();'play';}else{'no_video';}})()";
        }
        if ("pause".equals(action)) {
            return "(function(){var v=document.querySelector('video');if(v){v.pause();'pause';}else{'no_video';}})()";
        }
        if ("toggle".equals(action)) {
            return "(function(){try{var v=document.querySelector('video');if(!v)return 'no_video';if(v.paused||v.ended){v.play();return 'play';}else{v.pause();return 'pause';}}catch(e){return 'error';}})()";
        }
        return "(function(){var v=document.querySelector('video');if(v){v.pause();try{v.currentTime=0;}catch(e){}'stop';}else{'no_video';}})()";
    }
}
