package com.yieldbrowser.app;

final class ShieldScriptPartThree {
    private ShieldScriptPartThree() {
    }

    static String value() {
        return "function portalPopupTimer(fn){try{if(!adHeavyPortal())return false;var s=low(typeof fn==='function'?Function.prototype.toString.call(fn):fn);return /(?:\\bpopup\\b|\\bpopunder\\b|window\\.open\\s*\\(|open\\s*\\(\\s*['\"]https?:)/i.test(s);}catch(e){return false;}}"
                + "function fakeRewardAd(el){try{if(!downloadPage()||!visible(el))return false;var t=low((el.innerText||el.textContent||'').replace(/\\s+/g,' ')).trim();if(t.length<20||t.length>700)return false;var n=0;if(/get\\s*paid\\s*in\\s*\\d+\\s*minutes?/i.test(t))n++;if(/subscribe\\s*(?:&|and)?\\s*watch.*receive\\s*payment/i.test(t))n++;if(/\\badd\\s*cash\\b/i.test(t)&&/\\bcash\\s*out\\b/i.test(t))n++;if(/\\$\\s*[\\d,.]+\\s*available/i.test(t))n++;return n>=2;}catch(e){return false;}}"
                + "function rewardVictim(el){try{var v=el;for(var i=0;i<4&&v&&v.parentElement;i++){var p=v.parentElement;if(!fakeRewardAd(p))break;v=p;}return v;}catch(e){return el;}}"
                + "function downloadTakeoverText(el){try{if(!downloadPage()||!visible(el))return false;var r=el.getBoundingClientRect(),vw=Math.max(1,innerWidth),vh=Math.max(1,innerHeight);if((r.width*r.height)/(vw*vh)<0.55)return false;var t=low((el.innerText||el.textContent||'').replace(/\\s+/g,' ')).trim();var n=0;if(/(?:lucky\\s*77|slots?|casino|jackpot|togel)/i.test(t))n++;if(/(?:deposit|withdraw|promosi|bonus)/i.test(t))n++;if(/(?:masuk|daftar|register)/i.test(t))n++;if(/(?:telegram|live\\s*chat|olahraga)/i.test(t))n++;return n>=3;}catch(e){return false;}}"
                + "function overlayBad(el){try{if(!visible(el)||navControl(el)||downloadControl(el))return false;try{var safeChild=el.querySelector('a[href][rel=next],a[href][rel=prev],a[href][class*=next],a[href][class*=prev],a[href][class*=chapter],a[href][class*=download],[aria-label*=next i],[aria-label*=prev i],[aria-label*=download i]');if(safeChild&&(safeReaderNav(targetUrl(safeChild),safeChild)||safeDownloadNav(targetUrl(safeChild),safeChild)))return false;}catch(x){}var cs=getComputedStyle(el),r=el.getBoundingClientRect(),vw=Math.max(1,innerWidth),vh=Math.max(1,innerHeight);var cover=(r.width*r.height)/(vw*vh);if(cover<0.45)return false;var pos=cs.position;if(el.tagName!=='IFRAME'&&el.tagName!=='OBJECT'&&el.tagName!=='EMBED'&&pos!=='fixed'&&pos!=='absolute'&&pos!=='sticky')return false;var z=parseInt(cs.zIndex,10);if(!isFinite(z))z=0;var meta=low((el.id||'')+' '+(typeof el.className==='string'?el.className:'')+' '+(el.getAttribute&&el.getAttribute('aria-label')||''));var href=targetUrl(el)||el.src||el.data||'';var child='';try{var n=el.querySelector('a[href],iframe[src],object[data],embed[src],form[action]');if(n)child=n.href||n.src||n.data||n.action||'';}catch(x){}var marked=/(^|[ _-])(ad|ads|advert|popup|popunder|interstitial|clickunder|overlay|overplay|sponsor)([ _-]|$)/i.test(meta);var transparent=parseFloat(cs.opacity||'1')<0.18||cs.backgroundColor==='rgba(0, 0, 0, 0)'||cs.backgroundColor==='transparent';var clickable=!!(el.onclick||(el.getAttribute&&el.getAttribute('onclick'))||(el.getAttribute&&el.getAttribute('role'))==='link'||cs.cursor==='pointer');var meaningful=false;try{meaningful=!!el.querySelector('img,video,audio,[role=dialog],button,input,textarea,select')||String(el.innerText||el.textContent||'').trim().length>24;}catch(x){}var ph=host(location.href),ch=host(child||href);var thirdPartyTakeover=downloadPage()&&cover>0.45&&ch&&ph&&!same(ch,ph)&&!trustedDownloadHost(ch);return badNav(href,el)||badNav(child,el)||marked||thirdPartyTakeover||downloadTakeoverText(el)||(reader()&&cover>0.72&&z>=1000&&transparent&&clickable&&!meaningful);}catch(e){return false;}}"
                + "function clean(){if(!S.config.enabled)return;var removed=false;try{if(adHeavyPortal())D.querySelectorAll('#overplay,.overplay,[id*=overplay],[class*=overplay]').forEach(function(el){el.style.setProperty('display','none','important');el.style.setProperty('pointer-events','none','important');try{el.remove();}catch(x){}removed=true;});}catch(e){}try{var rw=D.querySelectorAll('div,section,aside,figure,a,p');for(var ri=rw.length-1;ri>=0;ri--){var re=rw[ri];if(!re||!re.isConnected)continue;if(fakeRewardAd(re)){var victim=rewardVictim(re);if(victim&&victim.isConnected){victim.remove();removed=true;}}}}catch(e){}try{if(S.config.resource)D.querySelectorAll('iframe[src],script[src],ins[data-ad-client]').forEach(function(el){var u=el.src||el.getAttribute('data-ad-client')||'';if(u&&bad(u,el)){el.remove();removed=true;}});}catch(e){}try{if(S.config.click)D.querySelectorAll('iframe,object,embed,[class*=popup],[class*=popunder],[class*=interstitial],[id*=popup],[id*=popunder],[id*=interstitial],[class*=overlay],[id*=overlay],[class*=overplay],[id*=overplay],[style*=z-index]').forEach(function(el){if(overlayBad(el)){el.style.setProperty('display','none','important');el.style.setProperty('pointer-events','none','important');try{el.remove();}catch(x){}removed=true;}});}catch(e){}if(removed){try{if(D.documentElement)D.documentElement.style.removeProperty('overflow');if(D.body)D.body.style.removeProperty('overflow');}catch(e){}}}"
                + "function schedule(){if(S.timer)return;S.timer=setTimeout(function(){S.timer=0;clean();},80);}"
                + "W.__yieldShieldV2SetConfig=function(n){try{if(n)Object.keys(n).forEach(function(k){S.config[k]=!!n[k];});schedule();}catch(e){}};"
                + "W.__yieldShieldV2Run=clean;"
                + "if(!S.installed){S.installed=true;"
                + "try{if(adHeavyPortal()){var nativeInterval=W.setInterval,nativeTimeout=W.setTimeout;W.setInterval=function(fn,delay){if(portalPopupTimer(fn))return 0;return nativeInterval.apply(W,arguments);};W.setTimeout=function(fn,delay){if(portalPopupTimer(fn))return 0;return nativeTimeout.apply(W,arguments);};}}catch(e){}"
                + "try{var nativeOpen=W.open;W.open=function(u,n,f){if(S.config.enabled&&Date.now()<=(S.downloadClickUntil||0)&&safeDownloadNav(u,null)){try{if(W.YieldAdBlockBridge&&YieldAdBlockBridge.onTrustedDownloadOpen){S.downloadClickUntil=0;YieldAdBlockBridge.onTrustedDownloadOpen(abs(u),String(location.href||''));return{closed:false,focus:function(){},close:function(){}};}}catch(x){}}if(S.config.enabled&&S.config.popup&&badNav(u,null)){report(u);return{closed:true,focus:function(){},close:function(){}};}try{return nativeOpen.call(W,u,n,f);}catch(e){return null;}};}catch(e){}"
                + "function listen(type,fn,touch){try{D.addEventListener(type,fn,touch?{capture:true,passive:false}:true);}catch(e){try{D.addEventListener(type,fn,true);}catch(x){}}}"
                + "function listenWindow(type,fn,touch){try{W.addEventListener(type,fn,touch?{capture:true,passive:false}:true);}catch(e){try{W.addEventListener(type,fn,true);}catch(x){}}}"
                + "listenWindow('click',clickGuard,false);listenWindow('auxclick',clickGuard,false);listen('submit',submitGuard,false);"
                + "['touchstart','touchend','pointerdown','pointerup','mousedown','mouseup'].forEach(function(t){listenWindow(t,shieldDownloadPress,true);listen(t,clickGuard,true);});"
                + "try{var ac=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(S.config.enabled&&S.config.click&&!safeDownloadNav(this.href,this)&&!safeReaderNav(this.href,this)&&badNav(this.href,this)){report(this.href);return;}return ac.call(this);};}catch(e){}"
                + "try{var fs=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){if(S.config.enabled&&S.config.redirect&&!safeDownloadNav(this.action,this)&&!safeReaderNav(this.action,this)&&badNav(this.action,this)){report(this.action);return;}return fs.call(this);};}catch(e){}"
                + "try{W.addEventListener('pageshow',function(){schedule();setTimeout(clean,180);},true);D.addEventListener('visibilitychange',function(){if(!D.hidden){clean();setTimeout(clean,180);}},true);}catch(e){}"
                + "try{S.observer=new MutationObserver(schedule);S.observer.observe(D.documentElement||D,{childList:true,subtree:true,attributes:true,attributeFilter:['src','href','action','style','class']});}catch(e){}"
                + "}"
                + "if(D.readyState==='loading')D.addEventListener('DOMContentLoaded',function(){clean();setTimeout(clean,350);},true);else schedule();";
    }
}
