package com.yieldbrowser.app;

final class ShieldScriptPartTwo {
    private ShieldScriptPartTwo() {
    }

    static String value() {
        return "function sameRelay(u,node){var a=abs(u),h=host(a),c=host(location.href),p=path(a);if(!h||!c||!same(h,c)||asset(a)||safeReaderNav(a,node)||safeDownloadNav(a,node)||contentPath(p))return false;var n=0;if(relay(a))n+=3;if(redirParam(a))n+=2;if(hardToken(a))n+=2;if(/(?:^|\\/)[a-z0-9_-]{16,}(?:\\/|$)/i.test(p))n+=1;if(reader()||downloadPage())n+=2;return n>=4;}"
                + "function bad(u,node){if(!S.config.enabled||!u)return false;var a=abs(u),l=low(a);if(/^(intent|market|shopeeid|lazada|tokopedia):/.test(l))return true;if(!/^https?:/i.test(a)||asset(a))return false;var h=host(a),c=host(location.href);if(safeDownloadNav(a,node)||safeReaderNav(a,node))return false;if(same(h,c))return S.config.redirect&&sameRelay(a,node);if(adHost(h)||hardToken(a))return true;if(downloadPage()||Date.now()<=(S.downloadClickUntil||0))return true;if(isolated())return true;return cheap(h)&&(redirParam(a)||/(?:^|\\/)[a-z0-9_-]{16,}(?:\\/|$)/i.test(path(a)));}"
                + "function readerTakeover(u){var a=abs(u),h=host(a),c=host(location.href);return reader()&&!!h&&!!c&&!same(h,c);}"
                + "function badNav(u,node){if(safeDownloadNav(u,node)||safeReaderNav(u,node))return false;if(bad(u,node))return true;var a=abs(u);if(!/^https?:/i.test(a)||asset(a))return false;var h=host(a),c=host(location.href);if(readerTakeover(a))return true;return isolated()&&!!h&&!!c&&!same(h,c);}"
                + "function report(u){try{var k=String(u||''),n=Date.now();if(k&&S.lastBlockedUrl===k&&n-(S.lastBlockedAt||0)<800)return;S.lastBlockedUrl=k;S.lastBlockedAt=n;if(W.YieldAdBlockBridge&&YieldAdBlockBridge.onAdRedirect)YieldAdBlockBridge.onAdRedirect(k);}catch(e){}}"
                + "function cancelEvent(e){try{if(e){e.preventDefault();e.stopPropagation();if(e.stopImmediatePropagation)e.stopImmediatePropagation();}}catch(x){}return false;}"
                + "function deny(e,u){try{if(u)report(u);}catch(x){}return cancelEvent(e);}"
                + "function targetUrl(node){try{var a=node&&node.closest?node.closest('a[href],area[href]'):null;if(a)return a.href||a.getAttribute('href')||'';var f=node&&node.closest?node.closest('form[action]'):null;if(f)return f.action||f.getAttribute('action')||'';}catch(e){}return'';}"
                + "function candidateUrl(node){try{var el=node&&node.closest?node.closest('a[href],area[href],form[action],button,[role=button],[role=link],[data-href],[data-url],[data-link],[data-next],[data-prev],[data-chapter-url]'):node;if(!el)return'';var direct=targetUrl(el);if(direct)return abs(direct);var attrs=['data-href','data-url','data-link','data-next','data-prev','data-chapter-url'];for(var i=0;i<attrs.length;i++){var v=el.getAttribute&&el.getAttribute(attrs[i]);if(v&&/^(?:https?:|\\/\\/|\\/|\\.\\.?\\/|\\?)/i.test(String(v).trim()))return abs(v);}var oc=el.getAttribute&&el.getAttribute('onclick')||'';var m=String(oc).match(/(?:window\\.)?location(?:\\.href)?\\s*=\\s*['\"]([^'\"]+)['\"]|location\\.(?:assign|replace)\\(\\s*['\"]([^'\"]+)['\"]/i);if(m)return abs(m[1]||m[2]);}catch(e){}return'';}"
                + "function rememberDownloadClick(node){try{if(!downloadControl(node))return false;S.downloadClickUntil=Date.now()+4000;if(W.YieldAdBlockBridge&&YieldAdBlockBridge.onTrustedDownloadGesture)YieldAdBlockBridge.onTrustedDownloadGesture(String(location.href||''));return true;}catch(e){return false;}}"
                + "function openTrustedDownloadClick(e,node,u){try{if(!e||(e.type!=='click'&&e.type!=='auxclick')||!u||!downloadControl(node))return false;var a=abs(u),h=host(a),c=host(location.href);if(!h||!c||same(h,c)||!trustedDownloadHost(h)||!safeDownloadNav(a,node))return false;if(!(W.YieldAdBlockBridge&&YieldAdBlockBridge.onTrustedDownloadOpen))return false;cancelEvent(e);S.downloadClickUntil=0;try{if(YieldAdBlockBridge.onTrustedDownloadGesture)YieldAdBlockBridge.onTrustedDownloadGesture(String(location.href||''));}catch(g){}YieldAdBlockBridge.onTrustedDownloadOpen(a,String(location.href||''));return true;}catch(x){return false;}}"
                + "function clickSurfaceSuspicious(node){try{var el=node&&node.closest?node.closest('a,button,[role=button],[role=link],[onclick],[style]'):node;if(!el||navControl(el)||downloadControl(el))return false;var u=candidateUrl(el);if(u&&badNav(u,el))return true;var cs=getComputedStyle(el),p=cs.position,z=parseInt(cs.zIndex,10);if(!isFinite(z))z=0;var meta=low((el.id||'')+' '+(typeof el.className==='string'?el.className:'')+' '+(el.getAttribute&&el.getAttribute('aria-label')||''));var transparent=parseFloat(cs.opacity||'1')<0.22||cs.backgroundColor==='rgba(0, 0, 0, 0)'||cs.backgroundColor==='transparent';var marked=/(^|[ _-])(ad|ads|advert|popup|popunder|interstitial|clickunder|overlay|sponsor)([ _-]|$)/i.test(meta);var clickable=!!(el.onclick||(el.getAttribute&&el.getAttribute('onclick'))||cs.cursor==='pointer'||el.tagName==='A'||el.tagName==='BUTTON');return clickable&&(marked||((p==='fixed'||p==='absolute'||p==='sticky')&&transparent&&z>=10));}catch(e){return false;}}"
                + "function eventPoint(e){try{var p=e;if(e&&e.changedTouches&&e.changedTouches.length)p=e.changedTouches[0];else if(e&&e.touches&&e.touches.length)p=e.touches[0];var x=p&&Number(p.clientX),y=p&&Number(p.clientY);return isFinite(x)&&isFinite(y)?{x:x,y:y}:null;}catch(x){return null;}}"
                + "function pointElements(e,blocked){try{var p=eventPoint(e);if(!p)return[];if(typeof D.elementsFromPoint==='function')return D.elementsFromPoint(p.x,p.y)||[];if(typeof D.elementFromPoint!=='function')return[];var style=blocked&&blocked.style,old=style?style.pointerEvents:'';if(style)style.pointerEvents='none';var below=D.elementFromPoint(p.x,p.y);if(style)style.pointerEvents=old;return below?[below]:[];}catch(x){return[];}}"
                + "function downloadAtPoint(e,blocked){try{if(!downloadPage()||!e)return null;var list=pointElements(e,blocked),seen=[];for(var i=0;i<list.length;i++){var raw=list[i],el=raw&&raw.closest?raw.closest('a[href],area[href],form[action],button,[role=button],[role=link],[data-href],[data-url],[data-link]'):null;if(!el||el===blocked||seen.indexOf(el)>=0)continue;seen.push(el);if(!downloadControl(el))continue;var u=candidateUrl(el);if(u&&trustedDownloadHost(host(u))&&safeDownloadNav(u,el))return{url:abs(u),node:el};}}catch(x){}return null;}"
                + "function recoverDownloadClick(e,blocked){try{if(!e||(e.type!=='click'&&e.type!=='auxclick'))return false;var hit=downloadAtPoint(e,blocked);if(!hit)return false;return openTrustedDownloadClick(e,hit.node,hit.url);}catch(x){return false;}}"
                + "function safeReaderAtPoint(e,blocked){try{if(!reader()||!e)return'';var list=pointElements(e,blocked),seen=[];for(var i=0;i<list.length;i++){var raw=list[i],el=raw&&raw.closest?raw.closest('a[href],area[href],button,[role=button],[role=link],[data-href],[data-url],[data-link],[data-next],[data-prev],[data-chapter-url]'):null;if(!el||el===blocked||seen.indexOf(el)>=0)continue;seen.push(el);var u=candidateUrl(el);if(u&&safeReaderNav(u,el))return abs(u);}}catch(x){}return'';}"
                + "function recoverReaderClick(e,blockedNode,blockedUrl){try{var safe=safeReaderAtPoint(e,blockedNode);if(!safe)return false;if(blockedUrl)deny(e,blockedUrl);else cancelEvent(e);if(S.readerNavLock)return true;S.readerNavLock=true;setTimeout(function(){try{location.assign(safe);}catch(x){try{location.href=safe;}catch(y){}}setTimeout(function(){S.readerNavLock=false;},500);},0);return true;}catch(x){return false;}}"
                + "function clickGuard(e){if(!S.config.enabled||!S.config.click||S.readerNavLock)return;try{rememberDownloadClick(e&&e.target);var blocked=e.target&&e.target.closest?e.target.closest('a,button,[role=button],[role=link],[onclick],[style]'):e.target;var u=candidateUrl(e.target);if(u&&openTrustedDownloadClick(e,e.target,u))return;if(recoverDownloadClick(e,blocked))return;if(u&&(safeDownloadNav(u,e.target)||safeReaderNav(u,e.target)))return;if(u&&badNav(u,e.target)){if(recoverReaderClick(e,blocked,u))return;return deny(e,u);}if(!u&&clickSurfaceSuspicious(e.target)&&recoverReaderClick(e,blocked,''))return;}catch(x){}}"
                + "function submitGuard(e){if(!S.config.enabled||!S.config.redirect)return;try{var f=e.target;if(f&&f.action&&(safeDownloadNav(f.action,f)||safeReaderNav(f.action,f)))return;if(f&&f.action&&badNav(f.action,f))return deny(e,f.action);}catch(x){}}"
                + "function visible(el){try{var r=el.getBoundingClientRect(),cs=getComputedStyle(el);return r.width>2&&r.height>2&&cs.display!=='none'&&cs.visibility!=='hidden';}catch(e){return false;}}";
    }
}
